#ifndef _MAIN_PROXY_SERVER_REDIRECT_H_
#define _MAIN_PROXY_SERVER_REDIRECT_H_

int qnj_proxy_server_redirect_socket, qnj_proxy_server_redirect_socket_client;
#define CLIENT_REQUEST_BUFFER 8192

#endif